language: python
python:
  - "2.7"

before_install:
  - . ./test.properties

script:
  - echo ${_TEST_ACCOUNT}
  - echo ${TEST_ACCOUNT}
  - echo ${TEST_ACCOUNT2}
  - echo ${TEST_USER}

after_success:
  - python hello.py ${TEST_ACCOUNT} ${TEST_ACCOUNT2}
  - echo ${TEST_ACCOUNT} > test_account.txt
  - cat test_account.txt