language: python
python:
  - "2.7"

before_install:
  - secure: TEST_ACCOUNT
  - . ./test.properties

script:
  - echo ${TEST_ACCOUNT}
  - echo ${TEST_USER}

after_success:
  - python hello.py