language: python
python:
  - "2.7"

env:
  global:
    - DEPLOY_TYPE="${DEPLOY_TYPE:-cf}"

before_install:
  - . ./test.properties

script:
  - echo ${_TEST_ACCOUNT}
  - echo ${TEST_ACCOUNT}
  - echo ${TEST_ACCOUNT2}
  - echo ${TEST_USER}
  - echo ${TEST_ACCOUNT} | base64
  - echo aaa
  - ./test.sh

after_success:
  - python hello.py ${TEST_ACCOUNT} ${TEST_ACCOUNT2}
  - echo ${TEST_ACCOUNT} > test_account.txt
  - cat test_account.txt

deploy:
  - DEPLOY_K="deploy_k"
  - provider: script
    skip_cleanup: true
    script:
      - ./test.sh


