language: python
python:
  - "2.7"

env:
  global:
  - secure: TEST_ACCOUNT

before_install:
  - . ./test.properties

script:
  - echo ${TEST_ACCOUNT}
  - echo ${TEST_USER}

after_success:
  - python hello.py